# Generated by Django 3.1.4 on 2022-02-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0037_auto_20220216_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='ica_code',
            name='sub_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ica_code',
            name='sub_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
